apiVersion: v1
kind: Service
metadata:
  name: operate
  labels:
    app: operate
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 8080
    protocol: TCP
  selector:
    app: operate