zeebe: "zeebe" #the zeebe service instance where operate will connect

service:
  type: ClusterIP
  port: 80

resources: 
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

